feat: Single movie page layout and content
rjsturing/rancid-tomatillos pull request #21
Opened 2023-12-02 03:25 UTC by rjsturing

# Description
- Implements `MovieDetail` component to display individual movie details when a movie is selected
  - Includes movie poster and backdrop images
  - Displays movie title, release date, and average rating
- Adds a "Back to Movies" button 
  - Reverts to displaying `Movies` component with all movie cards upon clearing the selection
- Enhances UI with basic styling for the `MovieDetail` view and back button

# Screenshot(s)
<img width="313" alt="Screenshot 2023-12-01 at 10 10 18 PM" src="https://github.com/rjsturing/rancid-tomatillos/assets/135551833/aa623043-62c2-4ca4-aa1a-dac603e9ec83">

# Notes
Need to resize or shift the way images are displayed so that there is less scrolling, and also change the date format

# Checklist
- [x] My PR has an appropriately descriptive and concise title.
- [x] My code follows the Turing Style Guides and best practices.
- [x] I ran the code locally and verified that there are no visible errors.
- [x] feat: My PR clearly describes what feature I'm adding and any changes needed to make it work.

2023-12-02 04:35 UTC, ericahagle requested changes
@rjsturing This is fantastic work! The only thing I think we should address before merging this PR is in my other comment about the backdrop image. Otherwise, I agree that it makes total sense to leave the other styling tweaks and stuff until after we finish functionality. Again, awesome job! 🚀

2023-12-02 04:35 UTC, ericahagle commented on src/MovieDetail/MovieDetail.js
> +        <img className="backdrop" src={movie.backdrop_path} alt={`${movie.title} backdrop`} />
@rjsturing I think this backdrop image is meant to basically be the background of the whole page (probably with some level of decreased opacity so the other elements are visible on top of it). I think maybe we need to wrap the rest of the stuff in a div or main or something, then give it a class, and turn it into a background through CSS—does that sound right?

2023-12-02 04:54 UTC, ericahagle commented on src/MovieDetail/MovieDetail.js
> +        <img className="backdrop" src={movie.backdrop_path} alt={`${movie.title} backdrop`} />
I just found a possible answer to this on a reddit post, which totally made sense—duh, we can probably utilize `useEffect` for this! 🤦 

```
useEffect(() => {
	if(someStateYouExpectToChangeToTriggerTheBackgroundChange === 'what you expect it to be to trigger the bg change') {
		document.body.style.backgroundImage = 'url(path/img.png)' // double check my quotes
	}
}, [someStateYouExpectToChangeToTriggerTheBackgroundChange])
```

Instead of using the actual paths tho, I think we should be able to use the prop. Or possibly instead of using `useEffect`, would could just insert `{document.body.style.backgroundImage = movie.backdrop_path}` into the return that's already there? Not sure which is the best option. Whaddya think?

2023-12-02 17:29 UTC, ericahagle approved these changes

2023-12-02 17:29 UTC, ericahagle commented on src/App/App.js
> +  }, [selectedMovie])
Yay! It worrrrrrksssss! Nicely done, @rjsturing! 🍪 

We can tweak the opacity and stuff like that later when we dig into the styling more.

2023-12-02 18:08 UTC, rjsturing commented on src/App/App.js
> +  }, [selectedMovie])
Tweaked opacity to reflect our discussion.

2023-12-02 18:09 UTC, merged

2023-12-04 20:22 UTC, nicktu12 commented on src/App/App.js
> +      document.body.style.background = `linear-gradient(rgba(255, 255, 255, 0.8), rgba(255, 255, 255, 0.8)), url(${selectedMovie.backdrop_path}) no-repeat center center fixed`;
This inline CSS is a bit hard to read - can you apply a class on line 29 that is present based on state updates instead? For example:
<main className={selectedMovie ? 'show-selected App' : 'App'}>