refactor: Remove hard to understand inline CSS
rjsturing/rancid-tomatillos pull request #38
Opened 2023-12-04 22:17 UTC by rjsturing

# Description
This pull request addresses the feedback regarding the inline CSS in the App.js file of the Rancid Tomatillos project. The inline CSS for dynamically setting the background image based on the selected movie was difficult to read and maintain. This PR introduces a class-based approach to apply styles based on state updates. Specifically, it modifies the main tag to use a dynamic class name that changes with the selectedMovie state, and handles the dynamic background image URL in the JavaScript code.

# Notes
reference: [_provide description here of what the PR is going to do to the code_
](https://github.com/rjsturing/rancid-tomatillos/pull/21/files#r1414444563)

# Checklist
- [x] My PR has an appropriately descriptive and concise title.
- [x] My code follows the Turing Style Guides and best practices.
- [x] I ran the code locally and verified that there are no visible errors.
- [x] fix: My PR clearly describes what bug I'm fixing and why.
- [x] refactor: My PR clearly describes what code I'm refactoring and why.

2023-12-04 23:33 UTC, ericahagle requested changes

2023-12-04 23:33 UTC, ericahagle commented on src/App/App.js
> -    } else {
@rjsturing Looks like we lost our transparency somehow on the backdrop. We should probably fix that before merging. Otherwise, looks pretty good to me!

2023-12-05 04:57 UTC, ericahagle requested changes
So, I'm not entirely sure why, but with this code the back button seems to be broken, and the background image isn't reaching all the way to the top of the page. Your original code works perfectly, so I don't want to merge these changes in until we can figure out how to keep our functionality in place. Maybe we can brainstorm some together tomorrow?

2023-12-05 06:26 UTC, ericahagle commented on src/App/App.css
> +}
@rjsturing If you add `overflow: auto;` to this, it fixes the whitespace issue.

2023-12-05 06:57 UTC, ericahagle commented on src/App/App.js
>    };
@rjsturing I think I figured out how to fix the broken image issue, too. 

Try this:
- On line 44, put it back to `setSelectedMovie(null);`
- Starting on line 30, change your `useEffect` to this:
```
useEffect(() => {
    if (selectedMovie) {
      const mainElement = document.querySelector('.show-selected');
      mainElement.style.backgroundImage = `url(${selectedMovie.backdrop_path})`;
    } else {
      const mainElement = document.querySelector('.App');
      mainElement.style.backgroundImage = 'none';
    }
  }, [selectedMovie]);
```

When I do that, I'm seeing it return to the main page properly and load all the movies with the usual white (non) background.

2023-12-05 14:00 UTC, rjsturing commented
I've fixed the issues you've pointed out, great catches. The back button functionality still seems to work for me. Please take a look when you're able to.

2023-12-05 22:01 UTC, ericahagle approved these changes
@rjsturing All working as expected now! Looks great! 🌯

2023-12-05 22:48 UTC, merged